# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-04 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0003_auto_20180804_1202'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('intro', models.CharField(max_length=250)),
                ('body', wagtail.core.fields.RichTextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='offerindexpage',
            name='body',
        ),
        migrations.AlterField(
            model_name='offerindexpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
