# Generated by Django 2.0.8 on 2018-08-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_offersubindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offerindexpage',
            name='intro',
        ),
        migrations.AddField(
            model_name='offersubindexpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='offerpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
