# Generated by Django 2.0.8 on 2018-08-08 17:06

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_contactdataemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactdataemail',
            name='model',
        ),
        migrations.AddField(
            model_name='contactformdata',
            name='content',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='data'),
        ),
        migrations.DeleteModel(
            name='ContactDataEmail',
        ),
    ]
