# Generated by Django 2.0.8 on 2018-08-08 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('home', '0016_auto_20180808_1906'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='policy_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
